### ISSUE TITLE
Upgrade Fly configuration

### ISSUE THREAD

**Issue by simonw** [natbat/pillarpointstewards#67]
Tips gathered from https://twitter.com/webology/status/1538197528809811968

This hack here: https://github.com/natbat/pillarpointstewards/blob/950e1a4771235d96e0ddd03e887daca3acaebfcc/Dockerfile#L22

Can be replaced like this: https://github.com/djangocon/grorg/blob/3c64a4a6286ac7743daf559ba836ebf21131af35/fly.toml#L11-L12

```toml
[deploy]
  release_command = "python manage.py migrate --noinput"
```
